// Generated by https://quicktype.io

// POST Auth - Login Usuario
// {{url}}/api/auth/login
export interface LoginResponse {
  ok:     boolean;
  msg:    string;
  person: Person;
  token:  string;
}

export interface Person {
  name:  string;
  role:  Role;
  email: string;
  uid:   string;
}

export interface Role {
  _id:  string;
  name: string;
}


// GET Auth - Revalidate login
// {{url}}/api/auth/renew

export interface ValidateAuth {
  ok:     boolean;
  msg:    string;
  person: Person;
  token:  string;
}

export interface Person {
  name:  string;
  role:  Role;
  email: string;
  uid:   string;
}

export interface Role {
  _id:  string;
  name: string;
}
