// Generated by https://quicktype.io

export interface LoginResponse {
  ok:     boolean;
  msg:    string;
  person: Person;
  token:  string;
}

export interface Person {
  name:  string;
  role:  Role;
  email: string;
  uid:   string;
}

export interface Role {
  _id:  string;
  name: string;
}
