// Generated by https://quicktype.io
/* 
  GET
  Courses - Get Cursos por Profesor
  {{url}}/api/courses/professor/62366100ec9c1639cbb445cb
*/
export interface ProfessorCoursesRes {
  ok:     boolean;
  msg:    string;
  cursos: Curso[];
}

export interface Curso {
  name:      string;
  professor: string;
  id:        string;
}
